# Generated by Django 5.2.5 on 2025-08-14 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0002_project_approval_amount_project_client_industry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostdata',
            name='backup_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='hostdata',
            name='cpu_usage',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='hostdata',
            name='disk_space',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='hostdata',
            name='linked_services',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hostdata',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hostdata',
            name='memory_usage',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='hostdata',
            name='operating_system',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hostdata',
            name='server_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hostdata',
            name='uptime',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
