# Generated by Django 5.2.5 on 2025-08-14 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0003_hostdata_backup_status_hostdata_cpu_usage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostdata',
            name='ssh_username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
