# Generated by Django 5.2.5 on 2025-08-14 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0004_hostdata_ssh_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='credentials_pass',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='domain',
            name='credentials_user',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='domain',
            name='dns_configured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='domain',
            name='linked_services',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='domain',
            name='nameservers',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='domain',
            name='renewal_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='domain',
            name='ssl_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='domain',
            name='ssl_installed',
            field=models.BooleanField(default=False),
        ),
    ]
