# Generated by Django 5.2.5 on 2025-08-18 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0005_domain_credentials_pass_domain_credentials_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='payment_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Advanced', 'Advanced'), ('Paid', 'Paid')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('Ongoing', 'Ongoing'), ('Completed', 'Completed'), ('On Hold', 'On Hold'), ('Cancelled', 'Cancelled')], default='Ongoing', max_length=20),
        ),
    ]
