# Generated by Django 5.2.5 on 2025-08-18 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0006_alter_project_payment_status_alter_project_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostdata',
            name='project',
        ),
        migrations.AddField(
            model_name='hostdata',
            name='project',
            field=models.ManyToManyField(blank=True, related_name='host_data', to='core_app.project'),
        ),
    ]
