# Generated by Django 5.2.5 on 2025-08-18 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0007_remove_hostdata_project_hostdata_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domain',
            name='project',
        ),
        migrations.AddField(
            model_name='domain',
            name='project',
            field=models.ManyToManyField(blank=True, related_name='domains', to='core_app.project'),
        ),
    ]
