# Generated by Django 5.2.5 on 2025-08-18 10:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0009_alter_user_options_user_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=30, unique=True, validators=[django.core.validators.RegexValidator(message='Username can contain letters, digits and @/./+/-/_ only.', regex='^[\\w.@+-]+$')]),
        ),
    ]
