# Generated by Django 5.2.5 on 2025-08-19 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0012_alter_project_project_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostdata',
            name='server_ip',
            field=models.GenericIPAddressField(blank=True, null=True, unique=True),
        ),
    ]
