# Generated by Django 5.2.5 on 2025-08-19 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0013_alter_hostdata_server_ip'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('company_address', models.TextField(blank=True)),
                ('company_phone', models.CharField(blank=True, max_length=50)),
                ('company_email', models.EmailField(blank=True, max_length=254)),
                ('quotation_no', models.CharField(max_length=50, unique=True)),
                ('date', models.DateField()),
                ('valid_until', models.DateField()),
                ('client_name', models.CharField(max_length=255)),
                ('client_contact', models.CharField(blank=True, max_length=255)),
                ('client_email', models.EmailField(blank=True, max_length=254)),
                ('client_address', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('web', 'Web Development'), ('mobile', 'Mobile Development'), ('cloud', 'Cloud Services'), ('ai_ml', 'AI/ML Algorithms')], max_length=100)),
                ('description', models.TextField(blank=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('service_unit_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_service_charge', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('domain_registration', models.JSONField(blank=True, null=True)),
                ('server_hosting', models.JSONField(blank=True, null=True)),
                ('ssl_certificate', models.JSONField(blank=True, null=True)),
                ('email_hosting', models.JSONField(blank=True, null=True)),
                ('total_server_domain_charge', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('discount_type', models.CharField(choices=[('flat', 'Flat'), ('percent', 'Percent')], default='flat', max_length=10)),
                ('discount_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('after_discount_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=18.0, max_digits=5)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('grand_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('payment_terms', models.TextField(blank=True)),
                ('additional_notes', models.TextField(blank=True)),
                ('signature', models.ImageField(blank=True, null=True, upload_to='signatures/')),
                ('signatory_name', models.CharField(blank=True, max_length=255)),
                ('signatory_designation', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prepared_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotations_prepared', to='core_app.user')),
            ],
        ),
    ]
