# Generated by Django 5.2.5 on 2025-08-19 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0014_quotation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='quotation_no',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
