# Generated by Django 5.2.5 on 2025-08-20 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0015_alter_quotation_quotation_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotation',
            name='category',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='description',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='service_unit_price',
        ),
        migrations.AddField(
            model_name='quotation',
            name='ai_ml_services',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='cloud_services',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='mobile_services',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='web_services',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
