# Generated by Django 5.2.5 on 2025-08-21 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0018_filedocs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filedocs',
            name='node_type',
        ),
    ]
