# Generated by Django 5.2.5 on 2025-08-25 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0021_projectpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpayment',
            name='payment_details',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projectpayment',
            name='milestone_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
