# Generated by Django 5.2.5 on 2025-08-26 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0023_designation_remove_user_designation_user_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='document_link',
            field=models.URLField(blank=True, help_text='Paste a valid document link (e.g., Google Drive, Dropbox, etc.)', max_length=500, null=True),
        ),
    ]
