# Generated by Django 5.2.5 on 2025-08-26 07:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0024_alter_user_document_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, unique=True, validators=[django.core.validators.EmailValidator(message='Enter a valid email address.')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, validators=[django.core.validators.MinLengthValidator(2, 'First name must be at least 2 characters.')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, validators=[django.core.validators.MinLengthValidator(2, 'Last name must be at least 2 characters.')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=30, unique=True, validators=[django.core.validators.RegexValidator(message='Username can contain letters, digits and @/./+/-/_ only.', regex='^[\\w.@+-]+$')]),
        ),
    ]
