# Generated by Django 5.2.5 on 2025-08-26 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0025_alter_user_email_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='lead_source',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
