# Generated by Django 5.2.5 on 2025-08-28 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0027_appmode_technology_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='discount_type',
            field=models.CharField(choices=[('none', 'None'), ('flat', 'Flat'), ('percent', 'Percent')], default='none', max_length=10),
        ),
    ]
