# Generated by Django 5.2.5 on 2025-08-28 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0028_alter_quotation_discount_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
