# Generated by Django 5.2.5 on 2025-08-28 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0029_alter_quotation_tax_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('Fixed', 'Fixed'), ('Salary', 'Salary Based')], default='Fixed', max_length=20),
        ),
    ]
