# Generated by Django 5.2.5 on 2025-09-01 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0031_rename_address_user_current_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='auto_renewal',
            field=models.CharField(blank=True, choices=[('Bank Transfer', 'Bank Transfer'), ('UPI', 'UPI'), ('Cash', 'Cash'), ('Cheque', 'Cheque'), ('Other', 'Other')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='domain',
            name='client_payment_status',
            field=models.CharField(choices=[('Received', 'Received'), ('Pending', 'Pending')], default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='domain',
            name='domain_charge',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Charge in INR', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='domain',
            name='payment_details',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='domain',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('Bank Transfer', 'Bank Transfer'), ('UPI', 'UPI'), ('Cash', 'Cash'), ('Cheque', 'Cheque'), ('Other', 'Other')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='domain',
            name='payment_mode',
            field=models.CharField(choices=[('Client', 'Client'), ('Company', 'Company')], default='Client', max_length=20),
        ),
        migrations.AddField(
            model_name='domain',
            name='sub_domain1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='domain',
            name='sub_domain2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
