# Generated by Django 5.2.5 on 2025-09-01 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0032_domain_auto_renewal_domain_client_payment_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hostdata',
            old_name='disk_space',
            new_name='RAM',
        ),
        migrations.RenameField(
            model_name='hostdata',
            old_name='memory_usage',
            new_name='memory',
        ),
        migrations.RemoveField(
            model_name='hostdata',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='hostdata',
            name='control_panel',
        ),
        migrations.RemoveField(
            model_name='hostdata',
            name='cpu_usage',
        ),
        migrations.RemoveField(
            model_name='hostdata',
            name='location',
        ),
        migrations.RemoveField(
            model_name='hostdata',
            name='uptime',
        ),
        migrations.AlterField(
            model_name='domain',
            name='auto_renewal',
            field=models.CharField(blank=True, choices=[('On', 'On'), ('Off', 'Off')], max_length=50, null=True),
        ),
    ]
