# Generated by Django 5.2.5 on 2025-09-01 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0033_rename_disk_space_hostdata_ram_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='salary',
            new_name='amount',
        ),
        migrations.AddField(
            model_name='user',
            name='fixed_employee_details',
            field=models.JSONField(blank=True, help_text='Stores amount, date, description for fixed employees in JSON format', null=True),
        ),
    ]
