# Generated by Django 5.2.5 on 2025-09-03 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0036_alter_user_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='employee_type',
            field=models.CharField(blank=True, choices=[('hourly', 'Hourly'), ('fixed', 'Fixed'), ('salary', 'Salary')], max_length=10, null=True),
        ),
    ]
