# Generated by Django 5.2.5 on 2025-09-03 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0037_alter_user_employee_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hourly_employee_details',
            field=models.JSONField(blank=True, help_text='Stores amount, date, description for hourly employees in JSON format', null=True),
        ),
    ]
