# Generated by Django 5.2.5 on 2025-09-03 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0038_user_hourly_employee_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='app_mode',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core_app.appmode'),
        ),
        migrations.AlterField(
            model_name='project',
            name='approval_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='client_industry',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='completed_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='contract_signed',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='data_folder',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='deadline',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='demo_given',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='developer_charge',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='expense',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='free_service',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='income',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='inquiry_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='lead_source',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='live_link',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='mediator_charge',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='other_link',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='payment_value',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='postman_collection',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='quotation_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='quotation_sent',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='server_charge',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='team_members',
            field=models.ManyToManyField(related_name='projects', to='core_app.user'),
        ),
        migrations.AlterField(
            model_name='project',
            name='technologies',
            field=models.ManyToManyField(to='core_app.technology'),
        ),
        migrations.AlterField(
            model_name='project',
            name='third_party_api_charge',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
