# Generated by Django 5.2.5 on 2025-09-03 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0041_project_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='client_payment_status',
            field=models.CharField(choices=[('None', 'None'), ('Received', 'Received'), ('Pending', 'Pending')], default='None', max_length=20),
        ),
    ]
