# Generated by Django 5.2.5 on 2025-09-03 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0042_alter_domain_client_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='client_payment_status',
            field=models.CharField(choices=[('None', 'None'), ('Received', 'Received'), ('Pending', 'Pending')], max_length=20),
        ),
        migrations.AlterField(
            model_name='domain',
            name='payment_mode',
            field=models.CharField(choices=[('None', 'None'), ('Client', 'Client'), ('Company', 'Company')], max_length=20),
        ),
    ]
