# Generated by Django 5.2.5 on 2025-09-04 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0045_subfolder_filedoc_subfolder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='amount',
            new_name='salary',
        ),
    ]
