# Generated by Django 5.2.5 on 2025-09-04 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0046_rename_amount_user_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='working_days',
            field=models.CharField(blank=True, help_text='Automatically calculated based on joining and last date', max_length=100, null=True),
        ),
    ]
