# Generated by Django 5.2.5 on 2025-09-04 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0047_user_working_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('Hourly', 'Hourly'), ('Fixed', 'Fixed'), ('Salary', 'Salary Based')], default='Fixed', max_length=20),
        ),
    ]
