# Generated by Django 5.2.5 on 2025-09-04 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0049_alter_project_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='payment_status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Advanced', 'Advanced'), ('Paid', 'Paid')], max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.CharField(blank=True, choices=[('Hourly', 'Hourly'), ('Fixed', 'Fixed'), ('Salary', 'Salary Based')], max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(blank=True, choices=[('In Progress', 'In Progress'), ('Completed', 'Completed'), ('On Hold', 'On Hold'), ('Cancelled', 'Cancelled')], max_length=20),
        ),
    ]
