# Generated by Django 5.2.5 on 2025-09-04 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0050_alter_project_payment_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='app_mode',
        ),
        migrations.AddField(
            model_name='project',
            name='app_modes',
            field=models.ManyToManyField(blank=True, related_name='projects', to='core_app.appmode'),
        ),
    ]
