# Generated by Django 5.2.5 on 2025-09-05 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0051_remove_project_app_mode_project_app_modes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='expense',
            new_name='other_expense',
        ),
        migrations.RemoveField(
            model_name='project',
            name='income',
        ),
    ]
