# Generated by Django 5.2.5 on 2025-09-06 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0052_rename_expense_project_other_expense_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectpayment',
            name='payment_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
