# Generated by Django 5.2.5 on 2025-09-06 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0053_alter_projectpayment_payment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='profit_loss',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
