# Generated by Django 5.2.5 on 2025-09-10 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0054_project_profit_loss'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='client_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
