# Generated by Django 5.2.5 on 2025-09-10 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0055_project_client_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='backend_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='frontend_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
