# Generated by Django 5.2.5 on 2025-09-15 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0056_project_backend_link_project_frontend_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='domain_charge',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
