# Generated by Django 5.2.5 on 2025-09-16 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0057_project_domain_charge'),
    ]

    operations = [
        migrations.AddField(
            model_name='filedoc',
            name='preview_file',
            field=models.FileField(blank=True, null=True, upload_to='previews/'),
        ),
    ]
