# Generated by Django 5.2.5 on 2025-09-16 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0058_filedoc_preview_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filedoc',
            name='preview_file',
        ),
    ]
