# Generated by Django 5.2.5 on 2025-09-16 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0059_remove_filedoc_preview_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeveloperPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('payment_method', models.CharField(blank=True, choices=[('Bank Transfer', 'Bank Transfer'), ('UPI', 'UPI'), ('Cash', 'Cash'), ('Cheque', 'Cheque'), ('Other', 'Other')], max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('payment_details', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core_app.user')),
                ('payment_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_made', to='core_app.user')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='developer_payments', to='core_app.project')),
            ],
        ),
    ]
