# Generated by Django 5.2.5 on 2025-09-18 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0060_developerpayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostdata',
            name='login_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
