# Generated by Django 5.2.5 on 2025-09-18 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0061_alter_hostdata_login_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostdata',
            name='ssh_password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
