# Generated by Django 5.2.5 on 2025-09-20 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0066_attendance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='status',
        ),
    ]
